### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by calculus0129** [Dongyeongkim/Dvote#1]
<h2>Entirely</h2> <h1><b>NOT</b></h1> the <i>Dvote</i> I know...<p>
And I'm not smart enough in codings to understand that now...
Reminds me of the old days...

**Comment by Dongyeongkim** [comment]
Lol my friend

This is Dvote that we taught about. using electric-signature system to verify the person's authority and make the message private to prevent the primary secret things; ballot. Read well and try to make it happen
